from fastapi import APIRouter, Depends, HTTPException, Query
from app.dependencies import get_current_user
from app.database import get_supabase_admin
from app.schemas.orders import OrderCreate
from app.services.bom_service import deduct_bom_for_order
from typing import Optional

router = APIRouter(prefix="/api/orders", tags=["Orders"])


@router.get("")
async def list_orders(
    payment_status: Optional[str] = Query(None),
    order_type: Optional[str] = Query(None),
    current_user: dict = Depends(get_current_user),
):
    """Danh sách hóa đơn theo chi nhánh."""
    sb = get_supabase_admin()
    query = (
        sb.table("orders")
        .select("*")
        .eq("branch_id", current_user["branch_id"])
        .order("created_at", desc=True)
    )
    if payment_status:
        query = query.eq("payment_status", payment_status)
    if order_type:
        query = query.eq("order_type", order_type)

    result = query.execute()
    return {"data": result.data, "count": len(result.data)}


@router.get("/{order_id}")
async def get_order(
    order_id: str,
    current_user: dict = Depends(get_current_user),
):
    """Chi tiết hóa đơn + line items."""
    sb = get_supabase_admin()
    order = (
        sb.table("orders")
        .select("*, order_details(*, menu_items(name, category))")
        .eq("id", order_id)
        .eq("branch_id", current_user["branch_id"])
        .maybe_single()
        .execute()
    )
    if not order.data:
        raise HTTPException(status_code=404, detail="Order not found")
    return {"data": order.data}


@router.post("")
async def create_order(
    body: OrderCreate,
    current_user: dict = Depends(get_current_user),
):
    """
    Tạo hóa đơn mới.
    - Tự động tính tổng tiền từ menu_items
    - Tự động trừ kho theo BOM
    - Ghi log inventory_transactions
    """
    sb = get_supabase_admin()
    branch_id = current_user["branch_id"]

    if not body.items:
        raise HTTPException(status_code=400, detail="Order must have at least one item")

    # Get menu item prices
    menu_ids = [item.menu_item_id for item in body.items]
    menu_result = (
        sb.table("menu_items")
        .select("id, price, name, is_available")
        .in_("id", menu_ids)
        .eq("branch_id", branch_id)
        .execute()
    )
    menu_map = {m["id"]: m for m in menu_result.data}

    # Validate items and calculate totals
    order_details = []
    total_amount = 0

    for item in body.items:
        menu_item = menu_map.get(item.menu_item_id)
        if not menu_item:
            raise HTTPException(status_code=404, detail=f"Menu item not found: {item.menu_item_id}")
        if not menu_item.get("is_available", True):
            raise HTTPException(status_code=400, detail=f"'{menu_item['name']}' is not available")

        subtotal = menu_item["price"] * item.quantity
        total_amount += subtotal
        order_details.append({
            "menu_item_id": item.menu_item_id,
            "quantity": item.quantity,
            "unit_price": menu_item["price"],
            "subtotal": subtotal,
            "notes": item.notes,
        })

    final_amount = total_amount - body.discount_amount

    # Create order (order_number auto-generated by trigger)
    order_data = {
        "branch_id": branch_id,
        "booking_id": body.booking_id,
        "order_type": body.order_type,
        "total_amount": total_amount,
        "discount_amount": body.discount_amount,
        "final_amount": final_amount,
        "notes": body.notes,
        "created_by": current_user["id"],
    }

    order_result = sb.table("orders").insert(order_data).execute()
    order = order_result.data[0]
    order_id = order["id"]

    # Insert order details
    for detail in order_details:
        detail["order_id"] = order_id
    sb.table("order_details").insert(order_details).execute()

    # BOM deduction
    await deduct_bom_for_order(
        order_id=order_id,
        branch_id=branch_id,
        items=[{"menu_item_id": d["menu_item_id"], "quantity": d["quantity"]} for d in order_details],
        created_by=current_user["id"],
    )

    # Return complete order
    final = (
        sb.table("orders")
        .select("*, order_details(*, menu_items(name))")
        .eq("id", order_id)
        .maybe_single()
        .execute()
    )
    return {"data": final.data, "message": "Order created with BOM deduction"}
